version: '3.5'
services:
    mariadbnode:
        image: 'mariadbnode'
        build: ./MariaDB/.
        container_name: 'marianode'
        environment: 
            - 'MYSQL_ROOT_PASSWORD=root'
        ports:
            - '3300:3306'
        healthcheck:
            test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
            timeout: 20s
            retries: 3
        networks: 
            node_net:
                ipv4_address: 172.25.0.28
    nodeapi:
        image: 'nodeapi'
        build: ./ApiMarca/.
        container_name: 'nodeapi'
        command: sh -c 'wait-for mariadbnode:3306'
        depends_on:
            - mariadbnode
        ports:
            - '3000:3000'
        networks: 
            node_net:
                ipv4_address: 172.25.0.30
    frontend:
        image: 'nodefrontend'
        build: ./Frontend/.
        container_name: 'nodeFrontend'
        depends_on: 
            - nodeapi
        ports: 
            - '8080:8080'
        networks: 
            node_net:
                ipv4_address: 172.25.0.31
        
networks: 
    node_net:
        ipam:
            driver: default
            config:
            - subnet: 172.25.0.0/16