version: '3.5'
services:
    bd:
        image: 'mariadbTPI'
        build: ./MariaDB/.
        container_name: 'mariatpi'
        environment: 
            - 'MYSQL_ROOT_PASSWORD=root'
        ports:
            - '3300:3306'
        networks: 
            mantenimiento_net:
                ipv4_address: 172.25.0.28
    apinode:
        image: 'nodetpi'
        build: ./Frontend/.
        container_name: 'nodetpi'
        depends_on:
            - db
        ports:
            - '3000:3000'
        networks: 
            mantenimiento_net:
                ipv4_address: 172.25.0.30
networks: 
    mantenimiento_net:
        ipam:
            driver: default
            config:
            - subnet: 172.25.0.0/16